#!/bin/bash

git_branch() {
  git_dir=$(git rev-parse --show-toplevel 2>/dev/null)
  if [ $? -eq 0 ]; then
    pushd "${git_dir}" >/dev/null
      branch=$(git branch --points-at=HEAD 2>/dev/null | grep -E '^\*' | tr -d '\n' | sed 's/^* //')
      if [ "$branch" == 'no branch' ]; then
        branch=$(git rev-list --abbrev-commit --max-count=1 HEAD)
      fi
    popd >/dev/null
    echo "${branch}"
  fi
}

git_prompt() {
  local red="\\[\\e[0;31m\\]"
  local green="\\[\\e[0;32m\\]"
  local reset_color="\[\e[39m\]"
  branch=$(git_branch)
  if [ -z "${branch}" ]; then
    return
  fi
  if [ "$(git status --porcelain | wc -l)" -gt 0 ]; then
    status="${red}✗${reset_color}"
  else
    status="${green}✓${reset_color}"
  fi
  echo "${reset_color}${status}${green} ${branch}${reset_color} ${reset_color}"
}

set_ps1() {
  local green="\\[\\e[0;32m\\]"
  local purple="\\[\\e[0;35m\\]"
  local cyan_bold="\\[\\e[36;1m\\]"
  local reset_color="\\[\\e[39m\\]"
  export PS1="
${cyan_bold}$(date +'%H:%M:%S') ${purple}\\h ${reset_color}in ${green}\\w
${cyan_bold}$(git_prompt)${green}→${reset_color} "

# export PS1="\W \$ "
}

PROMPT_COMMAND=set_ps1
